export { createDshAgentTool } from "./tools"
export type { DshAgentDeps } from "./tools"
export { runDshAcpAgent } from "./acp-client"
export type { DshAcpRunInput, DshAcpRunResult } from "./acp-client"
export { runDshHeadless } from "./headless-runner"
export type { DshHeadlessRunInput, DshHeadlessRunResult } from "./headless-runner"
export { runVerificationGate } from "./verify"
export type { VerificationInput, VerificationResult } from "./verify"
export { resolveDshAuth } from "./auth"
export type { DshAuth } from "./auth"
