export { detectChallenge, type DetectedChallenge } from "./detect"
export { solveCaptchaChain, SOLVER_PREFERENCE, type SolverName, type SolveResult, type SolverFn } from "./chain"
export { createSolverRegistry, type SolverRegistryOptions } from "./solvers"
export { resolveCapsolverKey } from "./api-key"
export { convertBrowserProxyToCapsolver, convertBrowserProxyToAntiCaptcha } from "./proxy-config"
export type { CapsolverProxyConfig } from "./capsolver-client"
export { CAPSOLVER_REGISTRY, getCapsolverHandler } from "./registry"
export type { CapsolverTaskHandler, CapsolverExtraction, CapsolverSolution } from "./registry-types"
export { ANTI_CAPTCHA_REGISTRY, getAntiCaptchaHandler } from "./anti-captcha-registry"
export type { AntiCaptchaTaskHandler, AntiCaptchaExtraction, AntiCaptchaRegistry } from "./anti-captcha-registry-types"
export type { AntiCaptchaTaskType, AntiCaptchaSolution } from "./anti-captcha-types"
export { buildAntiCaptchaSolver, type AntiCaptchaSolverOptions } from "./anti-captcha-solver"
export { createAntiCaptchaTask, pollAntiCaptchaTaskResult, getAntiCaptchaBalance } from "./anti-captcha-client"
