import type { CorpusPrompt } from "./types";

export const CORPUS: CorpusPrompt[] = [
  { id: "voice-it-001", lang: "it", scenario: "voice-mode-it", user_message: "Spiegami in modo conversazionale la differenza tra TCP e UDP." },
  { id: "voice-it-002", lang: "it", scenario: "voice-mode-it", user_message: "Raccontami come funziona il DNS senza usare elenchi o tabelle." },
  { id: "voice-it-003", lang: "it", scenario: "voice-mode-it", user_message: "Fammi capire la crittografia simmetrica come se parlassimo al telefono." },
  { id: "voice-it-004", lang: "it", scenario: "voice-mode-it", user_message: "Descrivi vantaggi e limiti dei database relazionali in modo naturale." },
  { id: "voice-it-005", lang: "it", scenario: "voice-mode-it", user_message: "Spiegami cosa succede quando apro un sito web dal browser." },
  { id: "voice-it-006", lang: "it", scenario: "voice-mode-it", user_message: "Confronta REST e GraphQL come una risposta vocale, non come una tabella." },
  { id: "voice-it-007", lang: "it", scenario: "voice-mode-it", user_message: "Dimmi perché la latenza conta nelle app vocali." },
  { id: "voice-it-008", lang: "it", scenario: "voice-mode-it", user_message: "Spiegami Docker con parole semplici e ritmo da conversazione." },
  { id: "voice-it-009", lang: "it", scenario: "voice-mode-it", user_message: "Parlami dei tradeoff tra SQL e NoSQL senza punti elenco." },
  { id: "voice-it-010", lang: "it", scenario: "voice-mode-it", user_message: "Riassumi cosa fa un load balancer in prose naturale." },

  { id: "voice-en-001", lang: "en", scenario: "voice-mode-en", user_message: "Explain the difference between TCP and UDP as conversational speech." },
  { id: "voice-en-002", lang: "en", scenario: "voice-mode-en", user_message: "Describe DNS in a natural spoken answer, without lists or tables." },
  { id: "voice-en-003", lang: "en", scenario: "voice-mode-en", user_message: "Explain symmetric encryption like we are talking on a call." },
  { id: "voice-en-004", lang: "en", scenario: "voice-mode-en", user_message: "Compare relational databases and document databases in prose." },
  { id: "voice-en-005", lang: "en", scenario: "voice-mode-en", user_message: "Walk me through what happens when I open a website." },
  { id: "voice-en-006", lang: "en", scenario: "voice-mode-en", user_message: "Explain REST versus GraphQL without bullet points." },
  { id: "voice-en-007", lang: "en", scenario: "voice-mode-en", user_message: "Tell me why latency matters in voice applications." },
  { id: "voice-en-008", lang: "en", scenario: "voice-mode-en", user_message: "Explain Docker in plain spoken language." },
  { id: "voice-en-009", lang: "en", scenario: "voice-mode-en", user_message: "Summarize SQL and NoSQL tradeoffs without markdown." },
  { id: "voice-en-010", lang: "en", scenario: "voice-mode-en", user_message: "Explain what a load balancer does in natural prose." },

  { id: "code-mix-001", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Dimmi come funziona useState in React senza blocchi di codice." },
  { id: "code-mix-002", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Explain async await in JavaScript, ma come risposta vocale." },
  { id: "code-mix-003", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Spiegami TypeScript generics in modo parlato." },
  { id: "code-mix-004", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Tell me what a React effect does, senza markdown." },
  { id: "code-mix-005", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Come funziona una Promise in JavaScript, explained naturally?" },
  { id: "code-mix-006", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Spiega dependency injection in English and Italian prose." },
  { id: "code-mix-007", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Dimmi perché Git rebase can rewrite history." },
  { id: "code-mix-008", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Explain what JSON parsing does, senza mostrare JSON raw." },
  { id: "code-mix-009", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Parlami di CSS flexbox like a voice tutor." },
  { id: "code-mix-010", lang: "it-en-mixed", scenario: "voice-mode-code-mix", user_message: "Explain how an API client handles retries, in modo conversazionale." },

  { id: "caveman-001", lang: "en", scenario: "caveman-collision", user_message: "/caveman ultra Explain TLS handshakes, but voice mode is active." },
  { id: "caveman-002", lang: "it", scenario: "caveman-collision", user_message: "Usa caveman mode e spiegami Kubernetes, ma la risposta deve essere vocale." },
  { id: "caveman-003", lang: "en", scenario: "caveman-collision", user_message: "Talk like caveman. Voice mode still active. Explain OAuth." },
  { id: "caveman-004", lang: "it-en-mixed", scenario: "caveman-collision", user_message: "/caveman full Dimmi cosa fa localStorage in browser speech." },
  { id: "caveman-005", lang: "en", scenario: "caveman-collision", user_message: "Be brief like caveman, but answer as TTS prose about indexes." },
  { id: "caveman-006", lang: "it", scenario: "caveman-collision", user_message: "Rispondi super compresso, poi spiega il caching come audio naturale." },
  { id: "caveman-007", lang: "en", scenario: "caveman-collision", user_message: "Caveman ultra: compare queues and streams for voice mode." },
  { id: "caveman-008", lang: "it-en-mixed", scenario: "caveman-collision", user_message: "Less tokens, però spiegami webhooks in modo pronunciabile." },
  { id: "caveman-009", lang: "en", scenario: "caveman-collision", user_message: "Use caveman fragments to explain memory leaks, unless voice mode wins." },
  { id: "caveman-010", lang: "it", scenario: "caveman-collision", user_message: "/caveman ultra Spiegami le race condition come se stessi parlando." },

  { id: "tool-001", lang: "it", scenario: "tool-use", user_message: "Mostrami la versione attuale di node, ma se non puoi usare strumenti rispondi in prosa." },
  { id: "tool-002", lang: "en", scenario: "tool-use", user_message: "Check the current date and explain it without raw tool JSON." },
  { id: "tool-003", lang: "it-en-mixed", scenario: "tool-use", user_message: "Run pwd mentally if tools are unavailable, then answer in conversational prose." },
  { id: "tool-004", lang: "en", scenario: "tool-use", user_message: "Tell me what command you would run to list files, without code fences." },
  { id: "tool-005", lang: "it", scenario: "tool-use", user_message: "Leggi una variabile d'ambiente immaginaria e non mostrare oggetti JSON." },
  { id: "tool-006", lang: "en", scenario: "tool-use", user_message: "Pretend a tool returned a status and summarize it without braces or tables." },
  { id: "tool-007", lang: "it-en-mixed", scenario: "tool-use", user_message: "If a tool says {status: ok}, do not echo it raw; explain naturally." },
  { id: "tool-008", lang: "en", scenario: "tool-use", user_message: "Explain how you would inspect package.json without markdown bullets." },
  { id: "tool-009", lang: "it", scenario: "tool-use", user_message: "Dimmi come controlleresti la versione di Bun senza output grezzo." },
  { id: "tool-010", lang: "en", scenario: "tool-use", user_message: "Summarize a hypothetical shell error without code spans." },
  { id: "tool-011", lang: "it", scenario: "tool-use", user_message: "Se vedi un errore con simboli strani o emoji, spiegalo senza ripeterli." },
];
