export const PROBE_LAB_MIGRATIONS: ReadonlyArray<string> = [
  "ALTER TABLE hypotheses ADD COLUMN question_id TEXT",
  "ALTER TABLE hypotheses ADD COLUMN uncertainty_label TEXT DEFAULT 'high'",
  "ALTER TABLE hypotheses ADD COLUMN superseded_by TEXT",
  "ALTER TABLE hypotheses ADD COLUMN resurrected_from TEXT",
  "ALTER TABLE hypotheses ADD COLUMN kb_premise_id TEXT",
  "ALTER TABLE hypotheses ADD COLUMN proposed_at INTEGER",
  "ALTER TABLE hypotheses ADD COLUMN activated_at INTEGER",
  "ALTER TABLE hypotheses ADD COLUMN confirmed_at INTEGER",
  "ALTER TABLE hypotheses ADD COLUMN refuted_at INTEGER",
  "ALTER TABLE probe_sessions ADD COLUMN experiment_id TEXT",
  "ALTER TABLE probe_sessions ADD COLUMN provider_id TEXT",
  "ALTER TABLE probe_sessions ADD COLUMN fingerprint_profile_id TEXT",
  "ALTER TABLE probe_sessions ADD COLUMN status TEXT DEFAULT 'running'",
  "ALTER TABLE probe_sessions ADD COLUMN identity_cost REAL DEFAULT 0.0",
  "ALTER TABLE probe_sessions ADD COLUMN duration_ms INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN sequence INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN host TEXT",
  "ALTER TABLE probe_exchanges ADD COLUMN path TEXT",
  "ALTER TABLE probe_exchanges ADD COLUMN request_body_size INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN response_body_size INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN timing_dns_ms INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN timing_connect_ms INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN timing_tls_ms INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN timing_first_byte_ms INTEGER",
  "ALTER TABLE probe_exchanges ADD COLUMN error_message TEXT",
  "ALTER TABLE probe_exchanges ADD COLUMN ciphered INTEGER DEFAULT 0",
  "ALTER TABLE probe_exchanges ADD COLUMN fingerprint_used TEXT",
  "ALTER TABLE probe_exchanges ADD COLUMN proxy_used TEXT",
  "ALTER TABLE probe_exchanges ADD COLUMN retry_count INTEGER DEFAULT 0",
  "ALTER TABLE evidence ADD COLUMN experiment_id TEXT",
  "ALTER TABLE evidence ADD COLUMN aspic_result TEXT",
  "ALTER TABLE evidence ADD COLUMN aspic_extensions_count INTEGER",
  "ALTER TABLE evidence ADD COLUMN aspic_accepted_conclusions TEXT",
  "ALTER TABLE evidence ADD COLUMN kb_entry_layer TEXT DEFAULT 'Learned'",
  "ALTER TABLE evidence ADD COLUMN previous_evidence_id INTEGER",
  "ALTER TABLE identities ADD COLUMN provider_id TEXT",
  "ALTER TABLE identities ADD COLUMN tier TEXT DEFAULT 'standard'",
  "ALTER TABLE identities ADD COLUMN lifetime_failures INTEGER DEFAULT 0",
  "ALTER TABLE identities ADD COLUMN lifetime_successes INTEGER DEFAULT 0",
  "ALTER TABLE identities ADD COLUMN total_requests INTEGER DEFAULT 0",
  "ALTER TABLE identities ADD COLUMN last_success_at INTEGER",
  "ALTER TABLE identities ADD COLUMN last_error_code TEXT",
  "ALTER TABLE identities ADD COLUMN quarantine_reason TEXT",
  "ALTER TABLE identities ADD COLUMN quarantine_count INTEGER DEFAULT 0",
  "ALTER TABLE identities ADD COLUMN max_quarantine_count INTEGER DEFAULT 5",
  "ALTER TABLE identities ADD COLUMN circuit_opened_at INTEGER",
  "ALTER TABLE identities ADD COLUMN fingerprint_profile_id TEXT",
  "ALTER TABLE identities ADD COLUMN session_affinity TEXT",
  "ALTER TABLE identities ADD COLUMN expires_at INTEGER",
]
