import { SUPPORTED_MODELS, SUPPORTED_PROVIDERS, SUPPORTED_VARIANTS } from "./registry"
import type { ModelRequirement } from "./model-requirement-types"

export const CATEGORY_MODEL_REQUIREMENTS: Record<string, ModelRequirement> = {
  "visual-engineering": {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.ANTHROPIC_API, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_5,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING, SUPPORTED_PROVIDERS.MOONSHOTAI, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.KIMI_K3,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ZAI_CODING_PLAN, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GLM_5_2,
        variant: SUPPORTED_VARIANTS.MAX,
      },
    ],
  },
  ultrabrain: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GITHUB_COPILOT],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_5,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
    ],
  },
  deep: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.QUOTIO_OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
    ],
  },
  artistry: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.ANTHROPIC_API, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_FABLE_5,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING, SUPPORTED_PROVIDERS.MOONSHOTAI, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.KIMI_K3,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.ANTHROPIC_API, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_5,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
    ],
  },
  quick: {
    fallbackChain: [
      { providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING], model: SUPPORTED_MODELS.KIMI_FOR_CODING_HIGHSPEED },
      { providers: [SUPPORTED_PROVIDERS.QUOTIO_OPENAI], model: SUPPORTED_MODELS.GPT_5_4_MINI_FAST, variant: SUPPORTED_VARIANTS.MINIMAL },
      { providers: [SUPPORTED_PROVIDERS.OPENAI], model: SUPPORTED_MODELS.GPT_5_4_MINI, variant: SUPPORTED_VARIANTS.MINIMAL },
      { providers: [SUPPORTED_PROVIDERS.XAI], model: SUPPORTED_MODELS.GROK_4_20_0309_NON_REASONING },
      { providers: [SUPPORTED_PROVIDERS.XIAOMI], model: SUPPORTED_MODELS.MIMO_V2_5_PRO_ULTRASPEED },
    ],
  },
  "unspecified-low": {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.QUOTIO_OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_LUNA,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GITHUB_COPILOT],
        model: SUPPORTED_MODELS.GPT_5_6_LUNA,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.ANTHROPIC_API, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_SONNET_5,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
      {
        providers: [SUPPORTED_PROVIDERS.QWEN_TOKEN_PLAN, SUPPORTED_PROVIDERS.ALIBABA_TOKEN_PLAN, SUPPORTED_PROVIDERS.QWEN_TOKEN_PLAN_CN, SUPPORTED_PROVIDERS.ALIBABA_TOKEN_PLAN_CN],
        model: SUPPORTED_MODELS.QWEN_3_8_MAX_PREVIEW,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.DEEPSEEK, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.DEEPSEEK_V4_PRO,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.XIAOMI, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.MIMO_V2_5_PRO,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.CURSOR], model: SUPPORTED_MODELS.COMPOSER_2_5 },
    ],
  },
  "unspecified-high": {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING, SUPPORTED_PROVIDERS.MOONSHOTAI, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.KIMI_K3,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.ANTHROPIC_API, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_5,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.QUOTIO_OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
    ],
  },
  writing: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING, SUPPORTED_PROVIDERS.MOONSHOTAI, SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.KIMI_K3,
        variant: SUPPORTED_VARIANTS.LOW,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.ANTHROPIC_API, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_5,
        variant: SUPPORTED_VARIANTS.LOW,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_6_FLASH,
      },
    ],
  },
};
