export const SUPPORTED_PROVIDERS = {
  ANTHROPIC: "anthropic",
  ANTHROPIC_API: "anthropic-api",
  GITHUB_COPILOT: "github-copilot",
  OPENCODE: "opencode",
  OPENCODE_GO: "opencode-go",
  VERCEL: "vercel",
  OPENAI: "openai",
  QUOTIO_OPENAI: "quotio-openai",
  GOOGLE: "google",
  KIMI_FOR_CODING: "kimi-for-coding",
  MOONSHOTAI: "moonshotai",
  MOONSHOTAI_CN: "moonshotai-cn",
  BAILIAN_CODING_PLAN: "bailian-coding-plan",
  FIRMWARE: "firmware",
  OLLAMA_CLOUD: "ollama-cloud",
  AIHUBMIX: "aihubmix",
  ZAI_CODING_PLAN: "zai-coding-plan",
  MINIMAX_CODING_PLAN: "minimax-coding-plan",
  MINIMAX_CN_CODING_PLAN: "minimax-cn-coding-plan",
  DEEPSEEK: "deepseek",
  XIAOMI: "xiaomi",
  QWEN_TOKEN_PLAN: "qwen-token-plan",
  ALIBABA_TOKEN_PLAN: "alibaba-token-plan",
  QWEN_TOKEN_PLAN_CN: "qwen-token-plan-cn",
  ALIBABA_TOKEN_PLAN_CN: "alibaba-token-plan-cn",
  XAI: "xai",
  CURSOR: "cursor",
} as const

export const SUPPORTED_MODELS = {
  CLAUDE_OPUS_5: "claude-opus-5",
  CLAUDE_SONNET_5: "claude-sonnet-5",
  CLAUDE_HAIKU_4_5: "claude-haiku-4-5",
  CLAUDE_FABLE_5: "claude-fable-5",
  GPT_5_6_SOL: "gpt-5.6-sol",
  GPT_5_6_TERRA: "gpt-5.6-terra",
  GPT_5_6_LUNA: "gpt-5.6-luna",
  GPT_5_4_MINI: "gpt-5.4-mini",
  GPT_5_4_MINI_FAST: "gpt-5.4-mini-fast",
  GPT_5_4_NANO: "gpt-5.4-nano",
  GPT_5_NANO: "gpt-5-nano",
  GEMINI_3_1_PRO: "gemini-3.1-pro",
  GEMINI_3_6_FLASH: "gemini-3.6-flash",
  KIMI_K3: "kimi-k3",
  KIMI_FOR_CODING_HIGHSPEED: "kimi-for-coding-highspeed",
  QWEN_3_7_PLUS: "qwen3.7-plus",
  QWEN_3_8_MAX_PREVIEW: "qwen3.8-max-preview",
  GLM_5_2: "glm-5.2",
  GLM_4_6V: "glm-4.6v",
  MINIMAX_M3: "minimax-m3",
  MINIMAX_M3_NATIVE: "MiniMax-M3",
  MINIMAX_M2_7: "minimax-m2.7",
  MINIMAX_M2_7_HIGHSPEED: "minimax-m2.7-highspeed",
  DEEPSEEK_V4_PRO: "deepseek-v4-pro",
  MIMO_V2_5_PRO: "mimo-v2.5-pro",
  MIMO_V2_5_PRO_ULTRASPEED: "mimo-v2.5-pro-ultraspeed",
  GROK_4_20_0309_NON_REASONING: "grok-4.20-0309-non-reasoning",
  COMPOSER_2_5: "composer-2.5",
  BIG_PICKLE: "big-pickle",
} as const

export const SUPPORTED_VARIANTS = {
  MAX: "max",
  XHIGH: "xhigh",
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low",
  MINIMAL: "minimal",
} as const
