/**
 * AGENTS.md Generator
 * 
 * Generates root AGENTS.md and architecture-specific AGENTS.md files
 * based on templates and project configuration.
 */

import * as fs from "fs";
import * as path from "path";
import type { TechStack, ProjectInfo } from "./tech-detection";
import type { InitProjectConfig, ArchitecturePattern, ArchitectureLayer } from "./config-generator";

// =============================================================================
// TEMPLATE LOADING
// =============================================================================

const TEMPLATES_PATH = ".opencode/templates";

export function loadTemplate(templatePath: string, projectPath: string): string | null {
  const fullPath = path.join(projectPath, TEMPLATES_PATH, templatePath);
  if (fs.existsSync(fullPath)) {
    return fs.readFileSync(fullPath, "utf-8");
  }
  return null;
}

// =============================================================================
// ROOT AGENTS.MD GENERATION
// =============================================================================

export function generateRootAgentsMd(config: InitProjectConfig): string {
  const { projectInfo, projectType, techStack, architecture, linear, mintlify } = config;
  const now = new Date().toISOString();

  // Languages section
  const languagesSection = techStack.languages.map((lang) => {
    let entry = `- **${lang.name}**`;
    if (lang.version) entry += ` v${lang.version}`;
    if (lang.primary) entry += ` (primary)`;
    return entry;
  }).join("\n");

  // Frameworks section
  let frameworksSection = "";
  if (techStack.frameworks.frontend) {
    frameworksSection += `- **Frontend**: ${techStack.frameworks.frontend.name}`;
    if (techStack.frameworks.frontend.version) {
      frameworksSection += ` v${techStack.frameworks.frontend.version}`;
    }
    frameworksSection += "\n";
  }
  if (techStack.frameworks.backend) {
    frameworksSection += `- **Backend**: ${techStack.frameworks.backend.name}`;
    if (techStack.frameworks.backend.version) {
      frameworksSection += ` v${techStack.frameworks.backend.version}`;
    }
    frameworksSection += "\n";
  }

  // Testing section
  let testingSection = "";
  if (techStack.frameworks.testing.length > 0) {
    testingSection = "### Testing Frameworks\n";
    for (const test of techStack.frameworks.testing) {
      testingSection += `- **${test.name}**`;
      if (test.version) testingSection += ` v${test.version}`;
      testingSection += "\n";
    }
  }

  // Database section
  let databaseSection = "";
  if (techStack.databases.length > 0) {
    databaseSection = "### Databases\n";
    for (const db of techStack.databases) {
      databaseSection += `- **${db.type}**`;
      if (db.name) databaseSection += ` (${db.name})`;
      if (db.orm) databaseSection += ` - ORM: ${db.orm}`;
      databaseSection += "\n";
    }
  }

  // Architecture layers
  const layersSection = architecture.layers.map((layer) => 
    `- \`${layer.path}/\` - ${layer.description}`
  ).join("\n");

  // Linear section
  let linearSection = "";
  if (linear.enabled) {
    linearSection = `### Linear (Project Management)
- **Team**: ${linear.teamName || linear.teamId || "Configured"}
${linear.projectId ? `- **Project**: ${linear.projectName || linear.projectId}` : ""}

#### Linear Workflow
- All significant work must have a Linear issue
- Get branch names from Linear before starting work
- ⚠️ Issues are REQUIRED for all work`;
  } else {
    linearSection = `### Linear (Project Management)
Linear integration not configured. Enable in \`.opencode/project-context.yaml\`.`;
  }

  // Mintlify section
  let mintlifySection = "";
  if (mintlify.enabled) {
    mintlifySection = `### Documentation
- **Platform**: Mintlify
- **Docs Path**: \`${mintlify.docsPath}\`
- **Config**: \`mint.json\`

API and architecture documentation should be maintained in Mintlify.`;
  } else {
    mintlifySection = `### Documentation
- All documentation in local markdown files
- Use AGENTS.md files for layer-specific instructions`;
  }

  return `# Project Instructions

> This file provides project-wide instructions for all AI agents.
> Generated by \`init-project\` command. Customize as needed.

## Project Overview

**Name**: ${projectInfo.name}
**Type**: ${projectType}
**Description**: ${projectInfo.description || "No description provided"}

## Technology Stack

### Languages
${languagesSection}

### Frameworks
${frameworksSection || "- None configured"}

${testingSection}

${databaseSection}

### Package Manager
- **${techStack.packageManager || "Not specified"}**

## Architecture

**Pattern**: ${architecture.name}

### Project Structure
${layersSection}

See architecture-specific AGENTS.md files in each layer directory for detailed instructions.

## Integrations

${linearSection}

${mintlifySection}

## Coding Conventions

### Naming
| Element | Convention |
|---------|------------|
| Files | \`kebab-case\` |
| Functions | \`camelCase\` |
| Classes | \`PascalCase\` |
| Constants | \`SCREAMING_SNAKE_CASE\` |
| Components | \`PascalCase\` |

### Code Style
- **Indentation**: 2 spaces
- **Quotes**: double
- **Semicolons**: yes
- **Trailing Commas**: yes
- **Max Line Length**: 100 characters

### Commits
**Format**: \`conventional\`

Pattern: \`<type>(<scope>): <description>\`

Example: \`feat(auth): add OAuth2 integration [LINEAR-123]\`

Valid scopes: \`feat\`, \`fix\`, \`docs\`, \`style\`, \`refactor\`, \`test\`, \`chore\`

### Branch Naming
Pattern: \`{type}/{issue-id}-{description}\`

Example: \`feature/LINEAR-123-add-user-auth\`

## Workflow Rules

### 1. Before Starting Work
${linear.enabled ? `- [ ] Ensure Linear issue exists (or create one)
- [ ] Get branch name from Linear issue` : ""}
- [ ] Read relevant AGENTS.md files for the areas you'll modify
- [ ] Pull latest changes from \`main\`
- [ ] Create feature branch following naming convention

### 2. During Work
- [ ] Follow architecture patterns defined in layer AGENTS.md files
- [ ] Keep commits atomic and well-described
- [ ] Update documentation as you code
- [ ] Add tests for new functionality
- [ ] Run linting and formatting before committing

### 3. After Completing Work
${linear.enabled ? `- [ ] Update Linear issue status
- [ ] Link PR to Linear issue` : ""}
- [ ] Create PR against \`main\`
- [ ] Ensure all CI checks pass
- [ ] Request code review
- [ ] Update AGENTS.md if architectural patterns changed

## References

- **Project Context**: \`.opencode/project-context.yaml\`
- **Architecture Templates**: \`.opencode/templates/architectures/\`
- **Agent Definitions**: \`.opencode/agent/\`
- **Instructions**: \`.opencode/instructions/\`

---

*This file was generated by OpenCode. Version: 1.0.0*
*Last updated: ${now}*
`;
}

// =============================================================================
// LAYER AGENTS.MD GENERATION
// =============================================================================

/**
 * Get the AGENTS.md template for a specific architecture layer
 */
export function getLayerTemplate(
  architecture: ArchitecturePattern,
  layer: ArchitectureLayer,
  projectPath: string,
): string | null {
  // Try to load from templates
  const templatePath = `architectures/${architecture.id}/${layer.agentsMd}`;
  return loadTemplate(templatePath, projectPath);
}

/**
 * Generate a layer-specific AGENTS.md file
 */
export function generateLayerAgentsMd(
  layer: ArchitectureLayer,
  architecture: ArchitecturePattern,
  config: InitProjectConfig,
  projectPath: string,
): string {
  // Try to load template
  const template = getLayerTemplate(architecture, layer, projectPath);
  
  if (template) {
    // Template exists, use it as-is (it's already customized for this layer)
    return template;
  }

  // No template found, generate a generic one
  return generateGenericLayerAgentsMd(layer, architecture, config);
}

/**
 * Generate a generic layer AGENTS.md when no template exists
 */
function generateGenericLayerAgentsMd(
  layer: ArchitectureLayer,
  architecture: ArchitecturePattern,
  config: InitProjectConfig,
): string {
  const { projectInfo, techStack } = config;
  const layerNameCapitalized = layer.name.charAt(0).toUpperCase() + layer.name.slice(1);

  // Determine primary language for code examples
  const primaryLang = techStack.languages.find((l) => l.primary)?.name || "TypeScript";
  const langLower = primaryLang.toLowerCase();

  return `# ${layerNameCapitalized} Layer

> Instructions for the **${layer.name}** layer of ${projectInfo.name}

## Purpose

${layer.description}

## Architecture Context

This layer is part of the **${architecture.name}** pattern.

**Path**: \`${layer.path}/\`

## Rules

### DO ✅

1. Keep ${layer.name} focused on their core responsibility
2. Follow established patterns in existing code
3. Write comprehensive tests for new code
4. Document complex business logic
5. Use dependency injection for external dependencies

### DON'T ❌

1. Don't mix concerns from other layers
2. Don't access database directly from this layer (if not data layer)
3. Don't bypass the established architecture
4. Don't create circular dependencies
5. Don't expose internal implementation details

## File Structure

\`\`\`
${layer.path}/
├── index.${langLower === "typescript" || langLower === "javascript" ? "ts" : langLower === "python" ? "py" : langLower}     # Public exports
├── types.${langLower === "typescript" || langLower === "javascript" ? "ts" : langLower === "python" ? "py" : langLower}     # Type definitions
└── __tests__/  # Tests for this layer
\`\`\`

## Patterns

### Creating New Files

When creating new files in this layer:

1. Follow the naming convention: \`kebab-case\`
2. Export from the \`index\` file
3. Include tests alongside the implementation
4. Add JSDoc/docstring comments for public APIs

### Example

\`\`\`${langLower === "typescript" ? "typescript" : langLower === "javascript" ? "javascript" : langLower}
// Example pattern for ${layer.name}
${getExampleCode(layer, primaryLang)}
\`\`\`

## Testing

- Write unit tests for all public functions
- Use mocks for external dependencies
- Aim for >80% coverage in this layer
- Test edge cases and error conditions

## Dependencies

This layer follows the ${architecture.name} dependency rules.
See the architecture documentation for allowed imports.

## Related

- **Project Overview**: \`/AGENTS.md\`
- **Architecture Docs**: \`.opencode/templates/architectures/${architecture.id}/\`
- **Project Context**: \`.opencode/project-context.yaml\`
`;
}

/**
 * Get example code snippet based on layer and language
 */
function getExampleCode(layer: ArchitectureLayer, language: string): string {
  const examples: Record<string, Record<string, string>> = {
    controllers: {
      TypeScript: `import { Request, Response } from "express";
import { UserService } from "../services/user-service";

export class UserController {
  constructor(private userService: UserService) {}

  async getUser(req: Request, res: Response) {
    const user = await this.userService.findById(req.params.id);
    res.json(user);
  }
}`,
      Python: `from fastapi import APIRouter, Depends
from ..services.user_service import UserService

router = APIRouter()

@router.get("/users/{user_id}")
async def get_user(user_id: str, service: UserService = Depends()):
    return await service.find_by_id(user_id)`,
    },
    services: {
      TypeScript: `import { UserRepository } from "../repositories/user-repository";
import { User } from "../models/user";

export class UserService {
  constructor(private userRepo: UserRepository) {}

  async findById(id: string): Promise<User | null> {
    return this.userRepo.findById(id);
  }
}`,
      Python: `from ..repositories.user_repository import UserRepository
from ..models.user import User

class UserService:
    def __init__(self, user_repo: UserRepository):
        self.user_repo = user_repo

    async def find_by_id(self, user_id: str) -> User | None:
        return await self.user_repo.find_by_id(user_id)`,
    },
    repositories: {
      TypeScript: `import { PrismaClient } from "@prisma/client";
import { User } from "../models/user";

export class UserRepository {
  constructor(private prisma: PrismaClient) {}

  async findById(id: string): Promise<User | null> {
    return this.prisma.user.findUnique({ where: { id } });
  }
}`,
      Python: `from sqlalchemy.orm import Session
from ..models.user import User

class UserRepository:
    def __init__(self, db: Session):
        self.db = db

    async def find_by_id(self, user_id: str) -> User | None:
        return self.db.query(User).filter(User.id == user_id).first()`,
    },
    domain: {
      TypeScript: `export interface User {
  id: string;
  email: string;
  name: string;
  createdAt: Date;
}

export class UserEntity implements User {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly name: string,
    public readonly createdAt: Date,
  ) {}

  isVerified(): boolean {
    // Business logic
    return this.email.includes("@verified.com");
  }
}`,
      Python: `from dataclasses import dataclass
from datetime import datetime

@dataclass
class User:
    id: str
    email: str
    name: str
    created_at: datetime

    def is_verified(self) -> bool:
        # Business logic
        return "@verified.com" in self.email`,
    },
  };

  const langKey = language === "JavaScript" ? "TypeScript" : language;
  const layerKey = layer.name.toLowerCase();

  // Try exact match
  if (examples[layerKey]?.[langKey]) {
    return examples[layerKey][langKey];
  }

  // Default example
  return `// Add your ${layer.name} implementation here
export function example() {
  // Implementation
}`;
}

// =============================================================================
// MAIN GENERATION FUNCTION
// =============================================================================

export async function generateAgentsMdFiles(
  projectPath: string,
  config: InitProjectConfig,
): Promise<string[]> {
  const createdFiles: string[] = [];
  const { architecture } = config;

  // Generate root AGENTS.md
  const rootAgentsMd = generateRootAgentsMd(config);
  const rootPath = path.join(projectPath, "AGENTS.md");
  fs.writeFileSync(rootPath, rootAgentsMd);
  createdFiles.push("AGENTS.md");

  // Generate layer-specific AGENTS.md files
  for (const layer of architecture.layers) {
    const layerDir = path.join(projectPath, layer.path);
    
    // Create directory if it doesn't exist
    if (!fs.existsSync(layerDir)) {
      fs.mkdirSync(layerDir, { recursive: true });
    }

    // Generate AGENTS.md
    const layerAgentsMd = generateLayerAgentsMd(layer, architecture, config, projectPath);
    const layerPath = path.join(layerDir, "AGENTS.md");
    fs.writeFileSync(layerPath, layerAgentsMd);
    createdFiles.push(`${layer.path}/AGENTS.md`);
  }

  return createdFiles;
}

// Note: All functions are exported at their definitions above

