import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

test("#given synced lcx-report-bug skill #when inspected #then it files LazyCodex bug issues with generated labels", async () => {
	// given
	const skillRoot = join(root, "skills", "lcx-report-bug");

	// when
	const skill = await readFile(join(skillRoot, "SKILL.md"), "utf8");
	const interfaceMetadata = await readFile(join(skillRoot, "agents", "openai.yaml"), "utf8");

	// then
	assert.match(skill, /^---\r?\nname: lcx-report-bug\r?\n/m);
	assert.match(skill, /code-yeongyu\/lazycodex/);
	assert.match(skill, /openai\/codex/);
	assert.match(skill, /\/tmp\/openai-codex-source/);
	assert.match(skill, /\$omo:debugging/);
	assert.match(skill, /Repository Decision/);
	assert.match(skill, /TARGET_REPO="code-yeongyu\/lazycodex" # or openai\/codex/);
	assert.match(skill, /gh issue create --repo "\$TARGET_REPO".*--label lazycodex-generated/);
	assert.match(skill, /gh pr create --repo "\$TARGET_REPO".*--label lazycodex-generated/);
	assert.match(skill, /lazycodex-generated/);
	assert.match(skill, /This issue or PR was generated by LazyCodex/);
	assert.match(skill, /Tag: lazycodex-generated/);
	assert.match(skill, /Browser use fallback/);
	assert.match(skill, /Computer use fallback/);
	assert.match(skill, /## Issue Body Template/);
	assert.match(interfaceMetadata, /display_name: "lcx-report-bug \(omo\)"/);
	assert.match(interfaceMetadata, /- "lazycodex bug"/);
	assert.match(interfaceMetadata, /- "openai codex bug"/);
});

test("#given synced lcx-contribute-bug-fix skill #when inspected #then it contributes LazyCodex bug-fix PRs from fresh temp workspaces", async () => {
	// given
	const skillRoot = join(root, "skills", "lcx-contribute-bug-fix");

	// when
	const skill = await readFile(join(skillRoot, "SKILL.md"), "utf8");
	const interfaceMetadata = await readFile(join(skillRoot, "agents", "openai.yaml"), "utf8");
	const script = await readFile(join(skillRoot, "scripts", "create-pr-body.mjs"), "utf8");

	// then
	assert.match(skill, /^---\r?\nname: lcx-contribute-bug-fix\r?\n/m);
	assert.match(skill, /Contribute a verified bug-fix PR/);
	assert.match(skill, /fresh `\/tmp` clone\/worktree/);
	assert.match(skill, /\/tmp\/lazycodex-fix-/);
	assert.match(skill, /git worktree add/);
	assert.match(skill, /lazycodex-generated/);
	assert.match(skill, /gh label create lazycodex-generated/);
	assert.match(skill, /gh pr create --repo "\$TARGET_REPO".*--label lazycodex-generated/);
	assert.match(skill, /scripts\/create-pr-body\.mjs/);
	assert.match(skill, /## Problem Situation/);
	assert.match(skill, /## Reproduction Logs/);
	assert.match(skill, /## Approach/);
	assert.match(skill, /## Why I Am Confident/);
	assert.match(skill, /## Risks/);
	assert.match(skill, /## User-Visible Behavior Changes/);
	assert.match(skill, /Clean up/);
	assert.match(interfaceMetadata, /display_name: "lcx-contribute-bug-fix \(omo\)"/);
	assert.match(interfaceMetadata, /- "contribute a bug fix"/);
	assert.match(interfaceMetadata, /- "fix bug pr"/);
	assert.match(script, /createLazyCodexBugFixPrBody/);
	assert.match(script, /Problem Situation/);
	assert.match(script, /Why I Am Confident/);
});
