import { z } from "zod";
export declare const BuiltinAgentNameSchema: z.ZodEnum<{
    atlas: "atlas";
    explore: "explore";
    hephaestus: "hephaestus";
    librarian: "librarian";
    metis: "metis";
    momus: "momus";
    "multimodal-looker": "multimodal-looker";
    oracle: "oracle";
    prometheus: "prometheus";
    sisyphus: "sisyphus";
    "sisyphus-junior": "sisyphus-junior";
}>;
export declare const BuiltinSkillNameSchema: z.ZodEnum<{
    "agent-browser": "agent-browser";
    debugging: "debugging";
    "dev-browser": "dev-browser";
    frontend: "frontend";
    "git-master": "git-master";
    "init-deep": "init-deep";
    playwright: "playwright";
    "remove-ai-slops": "remove-ai-slops";
    "review-work": "review-work";
    "security-research": "security-research";
    "security-review": "security-review";
    "team-mode": "team-mode";
    "visual-qa": "visual-qa";
}>;
export declare const OverridableAgentNameSchema: z.ZodEnum<{
    "OpenCode-Builder": "OpenCode-Builder";
    atlas: "atlas";
    build: "build";
    explore: "explore";
    hephaestus: "hephaestus";
    librarian: "librarian";
    metis: "metis";
    momus: "momus";
    "multimodal-looker": "multimodal-looker";
    oracle: "oracle";
    plan: "plan";
    prometheus: "prometheus";
    sisyphus: "sisyphus";
    "sisyphus-junior": "sisyphus-junior";
}>;
export declare const AgentNameSchema: z.ZodEnum<{
    atlas: "atlas";
    explore: "explore";
    hephaestus: "hephaestus";
    librarian: "librarian";
    metis: "metis";
    momus: "momus";
    "multimodal-looker": "multimodal-looker";
    oracle: "oracle";
    prometheus: "prometheus";
    sisyphus: "sisyphus";
    "sisyphus-junior": "sisyphus-junior";
}>;
export type AgentName = z.infer<typeof AgentNameSchema>;
export type BuiltinSkillName = z.infer<typeof BuiltinSkillNameSchema>;
