import type { OhMyOpenCodeConfig, HookName } from "../../config";
import type { BackgroundManager } from "../../features/background-agent";
import type { ModelFallbackControllerAccessor } from "../../hooks/model-fallback";
import type { ModelCacheState } from "../../plugin-state";
import type { PluginContext } from "../types";
import { createSessionNotification, createThinkModeHook, createModelFallbackHook, createAnthropicContextWindowLimitRecoveryHook, createAutoUpdateCheckerHook, createAstGrepSgProvisionHook, createAgentUsageReminderHook, createNonInteractiveEnvHook, createInteractiveBashSessionHook, createEditErrorRecoveryHook, createDelegateTaskRetryHook, createTaskResumeInfoHook, createUlwExecuteHook, createPrometheusMdOnlyHook, createSisyphusJuniorNotepadHook, createNoSisyphusGptHook, createNoHephaestusNonGptHook, createHephaestusAgentsMdInjectorHook, createQuestionLabelTruncatorHook, createPreemptiveCompactionHook, createRuntimeFallbackHook, createLegacyPluginToastHook } from "../../hooks";
import { createGoalHook } from "../../hooks/goal";
export type SessionHooks = {
    preemptiveCompaction: ReturnType<typeof createPreemptiveCompactionHook> | null;
    sessionNotification: ReturnType<typeof createSessionNotification> | null;
    thinkMode: ReturnType<typeof createThinkModeHook> | null;
    modelFallback: ReturnType<typeof createModelFallbackHook> | null;
    anthropicContextWindowLimitRecovery: ReturnType<typeof createAnthropicContextWindowLimitRecoveryHook> | null;
    autoUpdateChecker: ReturnType<typeof createAutoUpdateCheckerHook> | null;
    astGrepSgProvision: ReturnType<typeof createAstGrepSgProvisionHook> | null;
    agentUsageReminder: ReturnType<typeof createAgentUsageReminderHook> | null;
    nonInteractiveEnv: ReturnType<typeof createNonInteractiveEnvHook> | null;
    interactiveBashSession: ReturnType<typeof createInteractiveBashSessionHook> | null;
    goal: ReturnType<typeof createGoalHook> | null;
    editErrorRecovery: ReturnType<typeof createEditErrorRecoveryHook> | null;
    delegateTaskRetry: ReturnType<typeof createDelegateTaskRetryHook> | null;
    ulwExecute: ReturnType<typeof createUlwExecuteHook> | null;
    prometheusMdOnly: ReturnType<typeof createPrometheusMdOnlyHook> | null;
    sisyphusJuniorNotepad: ReturnType<typeof createSisyphusJuniorNotepadHook> | null;
    noSisyphusGpt: ReturnType<typeof createNoSisyphusGptHook> | null;
    noHephaestusNonGpt: ReturnType<typeof createNoHephaestusNonGptHook> | null;
    hephaestusAgentsMdInjector: ReturnType<typeof createHephaestusAgentsMdInjectorHook> | null;
    questionLabelTruncator: ReturnType<typeof createQuestionLabelTruncatorHook> | null;
    taskResumeInfo: ReturnType<typeof createTaskResumeInfoHook> | null;
    runtimeFallback: ReturnType<typeof createRuntimeFallbackHook> | null;
    legacyPluginToast: ReturnType<typeof createLegacyPluginToastHook> | null;
};
export declare function createSessionHooks(args: {
    ctx: PluginContext;
    pluginConfig: OhMyOpenCodeConfig;
    modelCacheState: ModelCacheState;
    backgroundManager: BackgroundManager;
    modelFallbackControllerAccessor?: ModelFallbackControllerAccessor;
    isHookEnabled: (hookName: HookName) => boolean;
    safeHookEnabled: boolean;
}): SessionHooks;
