import type { HookName, OhMyOpenCodeConfig } from "../../config";
import type { BackgroundManager } from "../../features/background-agent";
import type { MonitorManager } from "../../features/monitor";
import type { ModelFallbackControllerAccessor } from "../../hooks/model-fallback";
import type { PluginContext } from "../types";
import type { ModelCacheState } from "../../plugin-state";
export declare function createCoreHooks(args: {
    ctx: PluginContext;
    pluginConfig: OhMyOpenCodeConfig;
    modelCacheState: ModelCacheState;
    backgroundManager: BackgroundManager;
    modelFallbackControllerAccessor?: ModelFallbackControllerAccessor;
    monitorManager?: MonitorManager;
    isHookEnabled: (hookName: HookName) => boolean;
    safeHookEnabled: boolean;
}): {
    preemptiveCompaction: ReturnType<typeof import("../../hooks").createPreemptiveCompactionHook> | null;
    sessionNotification: ReturnType<typeof import("../../hooks").createSessionNotification> | null;
    thinkMode: ReturnType<typeof import("../../hooks").createThinkModeHook> | null;
    modelFallback: ReturnType<typeof import("../../hooks").createModelFallbackHook> | null;
    anthropicContextWindowLimitRecovery: ReturnType<typeof import("../../hooks").createAnthropicContextWindowLimitRecoveryHook> | null;
    autoUpdateChecker: ReturnType<typeof import("../../hooks").createAutoUpdateCheckerHook> | null;
    astGrepSgProvision: ReturnType<typeof import("../../hooks").createAstGrepSgProvisionHook> | null;
    agentUsageReminder: ReturnType<typeof import("../../hooks").createAgentUsageReminderHook> | null;
    nonInteractiveEnv: ReturnType<typeof import("../../hooks").createNonInteractiveEnvHook> | null;
    interactiveBashSession: ReturnType<typeof import("../../hooks").createInteractiveBashSessionHook> | null;
    goal: ReturnType<typeof import("../../hooks").createGoalHook> | null;
    editErrorRecovery: ReturnType<typeof import("../../hooks").createEditErrorRecoveryHook> | null;
    delegateTaskRetry: ReturnType<typeof import("../../hooks").createDelegateTaskRetryHook> | null;
    ulwExecute: ReturnType<typeof import("../../hooks").createUlwExecuteHook> | null;
    prometheusMdOnly: ReturnType<typeof import("../../hooks").createPrometheusMdOnlyHook> | null;
    sisyphusJuniorNotepad: ReturnType<typeof import("../../hooks").createSisyphusJuniorNotepadHook> | null;
    noSisyphusGpt: ReturnType<typeof import("../../hooks").createNoSisyphusGptHook> | null;
    noHephaestusNonGpt: ReturnType<typeof import("../../hooks").createNoHephaestusNonGptHook> | null;
    hephaestusAgentsMdInjector: ReturnType<typeof import("../../hooks").createHephaestusAgentsMdInjectorHook> | null;
    questionLabelTruncator: ReturnType<typeof import("../../hooks").createQuestionLabelTruncatorHook> | null;
    taskResumeInfo: ReturnType<typeof import("../../hooks").createTaskResumeInfoHook> | null;
    runtimeFallback: ReturnType<typeof import("../../hooks").createRuntimeFallbackHook> | null;
    legacyPluginToast: ReturnType<typeof import("../../hooks").createLegacyPluginToastHook> | null;
    commentChecker: ReturnType<typeof import("../../hooks").createCommentCheckerHooks> | null;
    toolOutputTruncator: ReturnType<typeof import("../../hooks").createToolOutputTruncatorHook> | null;
    directoryAgentsInjector: ReturnType<typeof import("../../hooks").createDirectoryAgentsInjectorHook> | null;
    directoryReadmeInjector: ReturnType<typeof import("../../hooks").createDirectoryReadmeInjectorHook> | null;
    emptyTaskResponseDetector: ReturnType<typeof import("../../hooks").createEmptyTaskResponseDetectorHook> | null;
    rulesInjector: ReturnType<typeof import("../../hooks").createRulesInjectorHook> | null;
    tasksTodowriteDisabler: ReturnType<typeof import("../../hooks").createTasksTodowriteDisablerHook> | null;
    writeExistingFileGuard: ReturnType<typeof import("../../hooks").createWriteExistingFileGuardHook> | null;
    bashFileReadGuard: ReturnType<typeof import("../../hooks").createBashFileReadGuardHook> | null;
    hashlineReadEnhancer: ReturnType<typeof import("../../hooks").createHashlineReadEnhancerHook> | null;
    jsonErrorRecovery: ReturnType<typeof import("../../hooks").createJsonErrorRecoveryHook> | null;
    readImageResizer: ReturnType<typeof import("../../hooks").createReadImageResizerHook> | null;
    todoDescriptionOverride: ReturnType<typeof import("../../hooks").createTodoDescriptionOverrideHook> | null;
    webfetchRedirectGuard: ReturnType<typeof import("../../hooks").createWebFetchRedirectGuardHook> | null;
    fsyncSkipWarning: ReturnType<typeof import("../../hooks").createFsyncSkipWarningHook> | null;
    teamToolGating: ReturnType<typeof import("../../hooks").createTeamToolGating> | null;
    notepadWriteGuard: ReturnType<typeof import("../../hooks").createNotepadWriteGuardHook> | null;
    planFormatValidator: ReturnType<typeof import("../../hooks").createPlanFormatValidatorHook> | null;
    claudeCodeHooks: ReturnType<typeof import("../../hooks").createClaudeCodeHooksHook> | null;
    keywordDetector: ReturnType<typeof import("../../hooks").createKeywordDetectorHook> | null;
    btwSideContextInjector: ReturnType<typeof import("../../features/btw-side").createBtwSideContextInjectorHook>;
    contextInjectorMessagesTransform: ReturnType<typeof import("../../features/context-injector").createContextInjectorMessagesTransformHook>;
    teamModeStatusInjector: ReturnType<typeof import("../../hooks").createTeamModeStatusInjector> | null;
    teamMailboxInjector: ReturnType<typeof import("../../hooks").createTeamMailboxInjector> | null;
    toolPairValidator: ReturnType<typeof import("../../hooks").createToolPairValidatorHook> | null;
    monitorStatusInjector: ReturnType<typeof import("../../hooks").createMonitorStatusInjectorHook> | null;
};
