import { afterEach, describe, expect, test } from "bun:test"
import { spawnSync } from "node:child_process"
import { appendFile, mkdtemp, readFile, rm, utimes, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { checkExtensionCurrent, toPortableBuildPath } from "./build-extension.mjs"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(scriptDir, "..", "..", "..", "..")
const tempRoots = []

// The extension build runs the bun build API in-process; bun:test intercepts those internal file
// reads ("Unexpected reading file"), so the test harness drives a build subprocess instead and
// parses the emitted artifact paths.
async function subprocessBuild(root) {
  const result = spawnSync(
    "bun",
    ["packages/omo-omp/plugin/scripts/build-extension.mjs", "--build-out", root],
    { cwd: repoRoot, encoding: "utf8" },
  )
  if (result.status !== 0) throw new Error(`extension build subprocess failed:\n${result.stderr ?? result.stdout}`)
  const omo = /^omo\.js=(.*)$/m.exec(result.stdout ?? "")?.[1]
  const member = /^omo-member\.js=(.*)$/m.exec(result.stdout ?? "")?.[1]
  if (typeof omo !== "string" || omo.length === 0 || typeof member !== "string" || member.length === 0) {
    throw new Error(`extension build subprocess output missing artifact paths:\n${result.stdout ?? ""}`)
  }
  return { outputPath: omo, memberOutputPath: member }
}

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })))
})

async function builtOutputs() {
  const root = await mkdtemp(join(repoRoot, ".build-extension-test-"))
  tempRoots.push(root)
  const { outputPath, memberOutputPath } = await subprocessBuild(root)
  // The build writes the metafile next to each artifact; the main bundle's inputs are what the
  // senpi-engine assertion inspects.
  const inputs = JSON.parse(
    spawnSync(
      "bun",
      ["-e", `const m = JSON.parse(require("fs").readFileSync(${JSON.stringify(`${outputPath}.meta.json`)}, "utf8")); console.log(JSON.stringify(Object.keys(m.inputs)))`],
      { cwd: repoRoot, encoding: "utf8" },
    ).stdout ?? "[]",
  )
  return { outputPath, memberOutputPath, mainInputs: inputs }
}

// The freshness check walks the build's full input list (including hoisted dependency sources under
// node_modules/.bun), which bun:test intercepts in-process; drive the real check as a subprocess.
async function checkViaSubprocess(outputPath) {
  const args = ["packages/omo-omp/plugin/scripts/build-extension.mjs", "--check"]
  if (typeof outputPath === "string") args.push("--output", outputPath)
  const result = spawnSync("bun", args, { cwd: repoRoot, encoding: "utf8" })
  return { ok: result.status === 0, output: result.stdout ?? "", error: result.stderr ?? "" }
}

describe("checkExtensionCurrent", () => {
  test("#given platform-specific source paths #when normalized #then build markers use portable separators", () => {
    expect(toPortableBuildPath("packages\\omo-omp\\src\\extension\\index.ts"))
      .toBe("packages/omo-omp/src/extension/index.ts")
    expect(toPortableBuildPath("packages/omo-omp/src/extension/index.ts"))
      .toBe("packages/omo-omp/src/extension/index.ts")
  })

  test("#given current generated outputs with old mtimes #when checked #then freshness passes", async () => {
    // given
    const outputs = await builtOutputs()
    const old = new Date(0)
    await Promise.all([utimes(outputs.outputPath, old, old), utimes(outputs.memberOutputPath, old, old)])

    // when
    const result = await checkViaSubprocess(outputs.outputPath)

    // then
    expect(result.ok).toBe(true)
  })

  test("#given changed generated bytes with future mtimes #when checked #then freshness fails", async () => {
    // given
    const outputs = await builtOutputs()
    await appendFile(outputs.outputPath, "\nchanged\n")
    const future = new Date("2100-01-01T00:00:00.000Z")
    await utimes(outputs.outputPath, future, future)

    // when
    const result = await checkViaSubprocess(outputs.outputPath)

    // then
    expect(result.ok).toBe(false)
    expect(result.error).toContain("stale-output")
  })

  test("#given intact generated bytes with a stale source digest #when checked #then source reproduction fails", async () => {
    // given
    const outputs = await builtOutputs()
    const artifact = await readFile(outputs.outputPath, "utf8")
    const newline = artifact.indexOf("\n")
    const [prefix, , bodyDigest] = artifact.slice(0, newline).split(":")
    await writeFile(outputs.outputPath, `${prefix}:${'0'.repeat(64)}:${bodyDigest}\n${artifact.slice(newline + 1)}`)

    // when
    const result = await checkViaSubprocess(outputs.outputPath)

    // then
    expect(result.ok).toBe(false)
    expect(result.error).toContain("stale-output")
  })

  test("#given freshly built outputs #when inspected #then normalization removes whitespace-only lines", async () => {
    // given
    const outputs = await builtOutputs()

    // when
    const main = await readFile(outputs.outputPath, "utf8")
    const member = await readFile(outputs.memberOutputPath, "utf8")

    // then
    expect(main).not.toMatch(/^[\t ]+$/m)
    expect(member).not.toMatch(/^[\t ]+$/m)
  })

  test("#given the main extension build #when its metafile inputs are inspected #then the senpi engine never rides inside the omp bundle", async () => {
    // given / when
    const inputs = (await builtOutputs()).mainInputs

    // then — the whole point of the omp adapter: the senpi ENGINE must not be bundled into the omp
    // extension (it is externalized; see OMP_LOADER_ALIASES). Its in-process runner modules are
    // tree-shaken away now that the omp task component runs children as OMP process sessions.
    expect(inputs.some((input) => input.includes("@code-yeongyu/senpi"))).toBe(false)
    expect(inputs.some((input) => input.endsWith("packages/senpi-task/src/runners/in-process.ts"))).toBe(false)
    expect(inputs.some((input) => input.endsWith("packages/senpi-task/src/runners/rpc-process.ts"))).toBe(true)
  })
})
