import type { ModelRegistry } from "./types"

export const MODEL_REGISTRY: ModelRegistry = {
  "claude-opus-4-6": {
    name: "Claude Opus 4.6",
    providers: ["anthropic", "github-copilot", "opencode"],
    capabilities: ["strong-reasoning", "code-generation", "long-context"],
    tier: "premium",
    speed: "normal",
    costPer1MInputTokens: 15,
    costPer1MOutputTokens: 45,
    contextWindow: 200000,
    isUnstable: false,
    family: "claude",
  },
  "claude-sonnet-4-6": {
    name: "Claude Sonnet 4.6",
    providers: ["anthropic", "github-copilot", "opencode"],
    capabilities: ["strong-reasoning", "code-generation", "long-context"],
    tier: "standard",
    speed: "normal",
    costPer1MInputTokens: 3,
    costPer1MOutputTokens: 15,
    contextWindow: 200000,
    isUnstable: false,
    family: "claude",
  },
  "claude-haiku-4-5": {
    name: "Claude Haiku 4.5",
    providers: ["anthropic", "github-copilot", "opencode"],
    capabilities: ["fast-inference", "code-generation"],
    tier: "economy",
    speed: "fast",
    costPer1MInputTokens: 0.8,
    costPer1MOutputTokens: 4,
    contextWindow: 200000,
    isUnstable: false,
    family: "claude",
  },
  "gpt-5.4": {
    name: "GPT-5.4",
    providers: ["openai", "github-copilot", "opencode"],
    capabilities: ["strong-reasoning", "code-generation", "multimodal"],
    tier: "premium",
    speed: "normal",
    costPer1MInputTokens: 30,
    costPer1MOutputTokens: 120,
    contextWindow: 128000,
    isUnstable: false,
    family: "gpt",
  },
  "gpt-5.3-codex": {
    name: "GPT-5.3 Codex",
    providers: ["openai", "venice", "opencode"],
    capabilities: ["autonomous-execution", "code-generation"],
    tier: "premium",
    speed: "normal",
    costPer1MInputTokens: 25,
    costPer1MOutputTokens: 100,
    contextWindow: 128000,
    isUnstable: false,
    family: "gpt",
  },
  "gpt-5-nano": {
    name: "GPT-5 Nano",
    providers: ["openai", "github-copilot", "opencode"],
    capabilities: ["fast-inference", "code-generation"],
    tier: "economy",
    speed: "fast",
    costPer1MInputTokens: 0.5,
    costPer1MOutputTokens: 2,
    contextWindow: 128000,
    isUnstable: false,
    family: "gpt",
  },
  "gemini-3.1-pro": {
    name: "Gemini 3.1 Pro",
    providers: ["google", "github-copilot", "opencode"],
    capabilities: ["strong-reasoning", "code-generation", "multimodal"],
    tier: "premium",
    speed: "normal",
    costPer1MInputTokens: 7.5,
    costPer1MOutputTokens: 30,
    contextWindow: 1000000,
    isUnstable: true,
    family: "gemini",
  },
  "gemini-3-flash": {
    name: "Gemini 3 Flash",
    providers: ["google", "github-copilot", "opencode"],
    capabilities: ["fast-inference", "code-generation", "multimodal"],
    tier: "economy",
    speed: "fast",
    costPer1MInputTokens: 0.075,
    costPer1MOutputTokens: 0.3,
    contextWindow: 1000000,
    isUnstable: true,
    family: "gemini",
  },
  "k2p5": {
    name: "Kimi K2.5",
    providers: ["kimi-for-coding"],
    capabilities: ["strong-reasoning", "code-generation", "long-context"],
    tier: "standard",
    speed: "normal",
    costPer1MInputTokens: 5,
    costPer1MOutputTokens: 15,
    contextWindow: 200000,
    isUnstable: true,
    family: "kimi",
  },
  "kimi-k2.5": {
    name: "Kimi K2.5",
    providers: [
      "opencode",
      "moonshotai",
      "moonshotai-cn",
      "firmware",
      "ollama-cloud",
      "aihubmix",
    ],
    capabilities: ["strong-reasoning", "code-generation", "long-context"],
    tier: "standard",
    speed: "normal",
    costPer1MInputTokens: 5,
    costPer1MOutputTokens: 15,
    contextWindow: 200000,
    isUnstable: true,
    family: "kimi",
  },
  "glm-5": {
    name: "GLM-5",
    providers: ["zai-coding-plan", "opencode"],
    capabilities: ["strong-reasoning", "code-generation"],
    tier: "standard",
    speed: "normal",
    costPer1MInputTokens: 8,
    costPer1MOutputTokens: 20,
    contextWindow: 128000,
    isUnstable: false,
    family: "glm",
  },
  "glm-4.6v": {
    name: "GLM-4.6V",
    providers: ["zai-coding-plan"],
    capabilities: ["strong-reasoning", "code-generation", "multimodal"],
    tier: "standard",
    speed: "normal",
    costPer1MInputTokens: 6,
    costPer1MOutputTokens: 18,
    contextWindow: 128000,
    isUnstable: false,
    family: "glm",
  },
  "minimax-m2.5-free": {
    name: "Minimax M2.5 Free",
    providers: ["opencode"],
    capabilities: ["code-generation", "instruction-following"],
    tier: "economy",
    speed: "fast",
    costPer1MInputTokens: 0,
    costPer1MOutputTokens: 0,
    contextWindow: 200000,
    isUnstable: true,
    family: "minimax",
  },
  "abab-5": {
    name: "Minimax ABAB 5",
    providers: ["opencode"],
    capabilities: ["code-generation", "instruction-following"],
    tier: "economy",
    speed: "fast",
    costPer1MInputTokens: 0,
    costPer1MOutputTokens: 0,
    contextWindow: 200000,
    isUnstable: true,
    family: "minimax",
  },
  "grok-code-fast-1": {
    name: "Grok Code Fast 1",
    providers: ["github-copilot"],
    capabilities: ["fast-inference", "code-generation"],
    tier: "economy",
    speed: "fast",
    costPer1MInputTokens: 1,
    costPer1MOutputTokens: 5,
    contextWindow: 128000,
    isUnstable: false,
    family: "grok",
  },
  "big-pickle": {
    name: "Big Pickle",
    providers: ["opencode"],
    capabilities: ["code-generation", "instruction-following"],
    tier: "economy",
    speed: "normal",
    costPer1MInputTokens: 0,
    costPer1MOutputTokens: 0,
    contextWindow: 128000,
    isUnstable: false,
    family: "big-pickle",
	},
}
