#!/usr/bin/env node
// Writes dist/v2/index.js: a thin re-export shim over the main bundle.
// The default export of dist/index.js is already the dual-host module (server + setup),
// so the ./v2 subpath only forwards to it instead of emitting a second full bundle.
import { mkdirSync, writeFileSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"

const root = process.cwd()
const outFile = join(root, "dist", "v2", "index.js")

// Precondition: the main bundle must exist (this node depends on the build graph's "index" node).
const mainEntry = join(root, "dist", "index.js")
if (!existsSync(mainEntry)) {
  console.error("[write-v2-shim] dist/index.js is missing; run the main build first")
  process.exit(1)
}

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  [
    "// Generated by script/write-v2-shim.mjs - do not edit.",
    "// Re-export of the dual-host default export (server + setup).",
    'import plugin from "../index.js";',
    "export default plugin;",
    "export const omoPlugin = plugin.server;",
    "export const omoPluginV2 = { id: plugin.id, setup: plugin.setup };",
    "",
  ].join("\n"),
  "utf8",
)
console.log("[write-v2-shim] written:", outFile)
