#!/usr/bin/env node
// 生成 dist/v2/index.js：对主 bundle 的轻量 re-export shim。
// 主 dist/index.js 默认导出已是 dual-host 模块（server + setup），
// ./v2 子路径只需转发，不产生第二份完整 bundle。
import { mkdirSync, writeFileSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"

const root = process.cwd()
const outFile = join(root, "dist", "v2", "index.js")

// 前置校验：主 bundle 必须存在（该节点依赖 build graph 的 index 节点）
const mainEntry = join(root, "dist", "index.js")
if (!existsSync(mainEntry)) {
  console.error("[write-v2-shim] dist/index.js 不存在，请先运行主构建")
  process.exit(1)
}

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  [
    "// Generated by script/write-v2-shim.mjs - do not edit.",
    "// Re-export of the dual-host default export (server + setup).",
    'import plugin from "../index.js";',
    "export default plugin;",
    "export const omoPlugin = plugin.server;",
    "export const omoPluginV2 = { id: plugin.id, setup: plugin.setup };",
    "",
  ].join("\n"),
  "utf8",
)
console.log("[write-v2-shim] written:", outFile)
