import { existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, rmSync, unlinkSync, writeFileSync, type Stats } from "node:fs"
import { homedir } from "node:os"
import { join, resolve } from "node:path"
import { pathToFileURL } from "node:url"

export type TargetInstallResult = {
  target: "oh-my-pi" | "pi"
  path: string
  installed: boolean
  conflict?: string
  removedDuplicates?: string[]
}

const duplicateExtensionNames = [
  "oh-my-openagent-dev",
  "oh-my-opencode",
  "oh-my-opencode-dev",
] as const

function maybeLstat(path: string): Stats | undefined {
  try {
    return lstatSync(path)
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined
    throw error
  }
}

function cleanupDuplicateInstalls(root: string, packageRoot: string): { removed: string[]; conflicts: string[] } {
  const removed: string[] = []
  const conflicts: string[] = []
  for (const name of duplicateExtensionNames) {
    const duplicatePath = join(root, name)
    const status = maybeLstat(duplicatePath)
    if (!status) continue

    if (status.isSymbolicLink()) {
      if (resolve(root, readlinkSync(duplicatePath)) === resolve(packageRoot)) {
        unlinkSync(duplicatePath)
        removed.push(duplicatePath)
      } else {
        conflicts.push(duplicatePath)
      }
      continue
    }

    if (status.isDirectory()) {
      const indexPath = join(duplicatePath, "index.js")
      const currentIndex = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : ""
      if (
        currentIndex.includes("Oh My OpenAgent target extension wrapper") &&
        currentIndex.includes(pathToFileURL(resolve(packageRoot)).href)
      ) {
        rmSync(duplicatePath, { recursive: true, force: true })
        removed.push(duplicatePath)
      } else {
        conflicts.push(duplicatePath)
      }
      continue
    }

    conflicts.push(duplicatePath)
  }
  return { removed, conflicts }
}

function installLink(target: TargetInstallResult["target"], root: string, packageRoot: string): TargetInstallResult {
  const path = join(root, "oh-my-openagent")
  const entry = target === "oh-my-pi" ? "dist/hosts/oh-my-pi/index.js" : "dist/hosts/pi/index.js"
  const entryPath = resolve(packageRoot, entry)
  const indexPath = join(path, "index.js")
  const packageJsonPath = join(path, "package.json")
  mkdirSync(root, { recursive: true })
  const duplicates = cleanupDuplicateInstalls(root, packageRoot)
  if (duplicates.conflicts.length > 0) {
    return {
      target,
      path,
      installed: false,
      conflict: `Duplicate OMO extension path was left untouched: ${duplicates.conflicts.join(", ")}`,
      removedDuplicates: duplicates.removed,
    }
  }
  const status = maybeLstat(path)
  if (status) {
    if (status.isSymbolicLink()) {
      if (resolve(root, readlinkSync(path)) !== resolve(packageRoot)) {
        return { target, path, installed: false, conflict: "Existing extension path was left untouched." }
      }
      unlinkSync(path)
    } else if (status.isDirectory()) {
      const currentIndex = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : ""
      if (!currentIndex.includes("Oh My OpenAgent target extension wrapper")) {
        return { target, path, installed: false, conflict: "Existing extension path was left untouched." }
      }
    } else {
      return { target, path, installed: false, conflict: "Existing extension path was left untouched." }
    }
  }
  mkdirSync(path, { recursive: true })
  writeFileSync(
    packageJsonPath,
    `${JSON.stringify({
      name: "oh-my-openagent-target-wrapper",
      type: "module",
      private: true,
      version: "0.0.0",
      [target === "oh-my-pi" ? "omp" : "pi"]: {
        extensions: ["./index.js"],
      },
    }, null, 2)}\n`,
  )
  writeFileSync(
    indexPath,
    `// Oh My OpenAgent target extension wrapper. Generated by install-targets.\nexport { default } from ${JSON.stringify(pathToFileURL(entryPath).href)}\n`,
  )
  return { target, path, installed: true, removedDuplicates: duplicates.removed }
}

export function installTargetExtensions(options: {
  packageRoot: string
  home?: string
  targets?: readonly ("oh-my-pi" | "pi")[]
}): TargetInstallResult[] {
  const home = options.home ?? homedir()
  const targets = options.targets ?? ["oh-my-pi", "pi"]
  return targets.map((target) =>
    installLink(
      target,
      target === "oh-my-pi" ? join(home, ".omp", "agent", "extensions") : join(home, ".pi", "agent", "extensions"),
      options.packageRoot,
    ),
  )
}
