export { createEpistemicStateInterpreterHook } from "./hook"
export type { EpistemicStateInterpreterHook, EpistemicStateInterpreterConfig } from "./hook"
export type { EpistemicState, EpistemicAnnotation, ClassifierInput, ProofChainKind } from "./types"
export type { TransitionID, TransitionRecord, HistoryEntry, ConclusionHistory } from "./transition-types"
export type { PersistedSessionState, PersistedConclusionData } from "./persistence-types"
export { computeDecay } from "./decay-engine"
export type { DecayInput, DecayOutput } from "./decay-engine"
export { enrichAnnotations } from "./annotation-enricher"
export { checkResurrection } from "./resurrection-engine"
export type { ResurrectionInput, ResurrectionOutput } from "./resurrection-engine"
export { computeTheoryHash } from "./theory-hasher"
export { resolveThresholds } from "./threshold-provider"
export type { ResolvedThresholds } from "./threshold-provider"
export { buildTransitionTable } from "./transition-table"
export { getSessionInvocationCount, incrementSessionInvocationCount } from "./history-store"
export { getAnnotations, clearAnnotations } from "./annotation-store"
export { clearHistory } from "./history-store"
export { storePreference, getPreferences, clearPreferences } from "./preference-store"

export { observeCalibration, clearCalibration } from "./calibration-observer"
export { observeGateResult, clearGateSuggester } from "./gate-mode-suggester"

export { createMultiPlaneHook } from "./hook-v2"
export type { MultiPlaneHookConfig, MultiPlaneHook } from "./hook-v2"
export type { AmmissibilitaState, ForzaQuantitativa, PotenzaInferenziale, DominanzaDecisionale, ValutazioneMultiAsse, MultiPlaneState, MultiPlaneAnnotation, EticoLabel, PragmaticoLabel, MoraleLabel, EticoOutput, PragmaticoOutput, MoraleOutput } from "./multi-plane-types"
export type { EpistemicHook, HookBalance, HookFactors, HookStrength, HookPolarity } from "./hook-entity-types"
export { classifyPianoA } from "./piano-a-classifier"
export { computePianoB } from "./piano-b-engine"
export { computePianoC } from "./piano-c-engine"
export { computePianoD } from "./piano-d-engine"
export type { PianoDInput } from "./piano-d-engine"
export { derivePreference, toValutazioneMultiAsse } from "./preference-derivation-v2"
export type { DerivedPreference, PreferenceDerivationInput } from "./preference-derivation-v2"
export { checkMultiPlaneGate } from "./gate-checker-v2"
export type { MultiPlaneGateResult } from "./gate-checker-v2"
export { deriveAspicPreferences, injectDerivedPreferences } from "./preference-injection-v2"
export { toEpistemicState, toEpistemicAnnotation } from "./backward-compat-bridge"
export { storeMultiPlaneAnnotations, getMultiPlaneAnnotations, clearMultiPlaneStore } from "./annotation-store-v2"

export { analyzeTagSemantics } from "./tag-semantic-analyzer"
export type { SemanticBonuses } from "./tag-semantic-analyzer"
