import type { TeamModeConfig } from "../../../config/schema/team-mode";
import { buildEnvelope } from "@oh-my-opencode/team-core/team-mailbox/poll";
import type { Message, RuntimeState } from "@oh-my-opencode/team-core/types";
import type { LiveDeliveryClient } from "./messaging-live-delivery-client";
import type { DeliveryReservation } from "./messaging-live-delivery-reservation";
import type { TeamSendMessageDispatchTiming } from "./messaging-runtime";
type RuntimeMember = RuntimeState["members"][number];
type LiveDeliveryEnvelope = ReturnType<typeof buildEnvelope>;
export declare function deliverLiveToRecipient(input: {
    client: LiveDeliveryClient;
    message: Message;
    envelope: LiveDeliveryEnvelope;
    teamRunId: string;
    recipientName: string;
    recipientMember: RuntimeMember;
    reservation: DeliveryReservation;
    config: TeamModeConfig;
    directory: string;
    settleMs?: number;
    dispatchTiming?: TeamSendMessageDispatchTiming;
}): Promise<void>;
export {};
