// Curated lists for friendly session names. Kept short, lower-case, hyphen-safe.
// Picked words are common, recognizable, and produce readable combos like
// "strawberry-carrot" or "mango-spinach".

export const FRUITS = [
  "apple",
  "apricot",
  "banana",
  "blackberry",
  "blueberry",
  "cherry",
  "coconut",
  "cranberry",
  "fig",
  "grape",
  "guava",
  "kiwi",
  "lemon",
  "lime",
  "lychee",
  "mango",
  "melon",
  "nectarine",
  "orange",
  "papaya",
  "passionfruit",
  "peach",
  "pear",
  "persimmon",
  "pineapple",
  "plum",
  "pomegranate",
  "raspberry",
  "rhubarb",
  "strawberry",
  "tangerine",
  "watermelon",
] as const

export const VEGETABLES = [
  "artichoke",
  "arugula",
  "asparagus",
  "avocado",
  "beet",
  "broccoli",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chard",
  "chickpea",
  "corn",
  "cucumber",
  "eggplant",
  "endive",
  "fennel",
  "garlic",
  "ginger",
  "kale",
  "leek",
  "lentil",
  "lettuce",
  "mushroom",
  "okra",
  "onion",
  "parsnip",
  "pea",
  "pepper",
  "potato",
  "pumpkin",
  "radish",
  "shallot",
  "spinach",
  "squash",
  "tomato",
  "turnip",
  "watercress",
  "yam",
  "zucchini",
] as const

export type Fruit = (typeof FRUITS)[number]
export type Vegetable = (typeof VEGETABLES)[number]
